### ISSUE TITLE
Doenst compile on real device

### ISSUE THREAD

**Issue by rebotnix** [jasongorski/libbpg-xcode#1]
i tried to run the project on a iOS iphone 6 device, but it only compiles in the simulator. The error message is 

../libbpg-xcode-master/jctvc/TLibEncoder/AnnexBwrite.h:73:17: Cannot initialize a parameter of type 'const char_type *' (aka 'const char *') with an lvalue of type 'const Char [4]'

../libbpg-xcode-master/jctvc/TLibCommon/TComSlice.cpp:2123:18: No matching function for call to 'fopen'

I tried to set compiler flags to -Objc++, but it doenst helped. Do you have an idea to compile it for iOS device?

**Comment by jasongorski** [comment]
Char was setup to be unsigned for ARM platforms. It appears as though on iOS at least, signed is the default. Builds now. Thanks for report.
